import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Brain,
  ArrowRight,
  Sparkles,
  Target,
  BarChart3,
  Users,
  Shield,
  Zap,
  Mail,
  Github,
  Linkedin,
} from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Questions",
    desc: "Dynamic questions generated by advanced AI, tailored to your level and target role.",
  },
  {
    icon: Target,
    title: "Real-Time Feedback",
    desc: "Get instant, detailed evaluation of your answers with actionable improvement suggestions.",
  },
  {
    icon: BarChart3,
    title: "Performance Analytics",
    desc: "Track your progress across categories with detailed charts and insights.",
  },
  {
    icon: Users,
    title: "Multiple Formats",
    desc: "Practice aptitude, technical, HR, and managerial interviews in one platform.",
  },
  {
    icon: Shield,
    title: "Adaptive Difficulty",
    desc: "Questions adjust to your skill level for the most effective practice sessions.",
  },
  {
    icon: Zap,
    title: "Instant Results",
    desc: "Comprehensive scorecards with grades, strengths, and areas to improve.",
  },
];

const categories = [
  {
    name: "Aptitude",
    color: "from-indigo-500 to-blue-500",
    desc: "Logical reasoning & quantitative skills",
  },
  {
    name: "Technical",
    color: "from-violet-500 to-purple-500",
    desc: "DSA, system design & programming",
  },
  {
    name: "HR",
    color: "from-pink-500 to-rose-500",
    desc: "Behavioral & situational questions",
  },
  {
    name: "Managerial",
    color: "from-amber-500 to-orange-500",
    desc: "Leadership & strategic thinking",
  },
];

const fadeUp = {
  initial: { opacity: 0, y: 30 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] },
};

export default function Landing() {
  return (
    <div className="min-h-screen bg-[var(--color-bg)]">
      {/* Nav */}
      <nav className="fixed top-0 w-full z-50 bg-white/80 dark:bg-surface-950/80 backdrop-blur-xl border-b border-surface-100 dark:border-surface-800">
        <div className="section-padding flex items-center justify-between h-16">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <span className="text-lg font-semibold tracking-tight">
              InterviewAI
            </span>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login" className="btn-ghost text-sm">
              Sign In
            </Link>
            <Link to="/register" className="btn-primary text-sm py-2 px-5">
              Get Started <ArrowRight className="w-4 h-4 ml-1" />
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="pt-32 pb-20 section-padding">
        <motion.div className="max-w-4xl mx-auto text-center" {...fadeUp}>
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-50 dark:bg-primary-950/50 text-primary-600 dark:text-primary-400 text-sm font-medium mb-8">
            <Sparkles className="w-4 h-4" />
            AI-Powered Interview Preparation
          </div>

          <h1 className="text-display-lg max-sm:text-display gradient-text mb-6 text-balance">
            Practice Like a Real Interview
          </h1>

          <p className="text-xl text-[var(--color-text-secondary)] max-w-2xl mx-auto mb-10 text-balance leading-relaxed">
            InterviewAI gives you realistic mock rounds, specific feedback for
            each answer, and a clear path to improve before your actual
            interview.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              to="/register"
              className="btn-primary text-base py-3.5 px-8 w-full sm:w-auto"
            >
              Start Practicing Free <ArrowRight className="w-5 h-5 ml-2" />
            </Link>
            <Link
              to="/login"
              className="btn-secondary text-base py-3.5 px-8 w-full sm:w-auto"
            >
              Sign In to Dashboard
            </Link>
          </div>
        </motion.div>
      </section>

      {/* Categories */}
      <section className="py-20 section-padding">
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
        >
          <h2 className="text-display-sm mb-4">
            Four Pillars of Interview Prep
          </h2>
          <p className="text-lg text-[var(--color-text-secondary)]">
            Master every interview format with specialized practice modules.
          </p>
        </motion.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-5xl mx-auto">
          {categories.map((cat, i) => (
            <motion.div
              key={cat.name}
              className="card-hover text-center"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1, duration: 0.5 }}
            >
              <div
                className={`w-14 h-14 mx-auto mb-4 rounded-2xl bg-gradient-to-br ${cat.color} flex items-center justify-center shadow-lg`}
              >
                <span className="text-2xl text-white font-bold">
                  {cat.name.charAt(0)}
                </span>
              </div>
              <h3 className="text-lg font-semibold mb-2">{cat.name}</h3>
              <p className="text-sm text-[var(--color-text-secondary)]">
                {cat.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="py-20 bg-surface-50 dark:bg-surface-950 section-padding">
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
        >
          <h2 className="text-display-sm mb-4">
            Everything You Need to Succeed
          </h2>
          <p className="text-lg text-[var(--color-text-secondary)]">
            A comprehensive platform designed for serious interview preparation.
          </p>
        </motion.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8 max-w-5xl mx-auto">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              className="card"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.08, duration: 0.5 }}
            >
              <div className="w-12 h-12 rounded-2xl bg-primary-100 dark:bg-primary-900/30 flex items-center justify-center mb-4">
                <feature.icon className="w-6 h-6 text-primary-600 dark:text-primary-400" />
              </div>
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">
                {feature.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 section-padding">
        <motion.div
          className="max-w-3xl mx-auto text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h2 className="text-display-sm mb-6 text-balance">
            Ready to Transform Your Interview Skills?
          </h2>
          <p className="text-lg text-[var(--color-text-secondary)] mb-10">
            Join thousands of candidates who improved their interview
            performance with AI-powered practice.
          </p>
          <Link to="/register" className="btn-primary text-base py-3.5 px-8">
            Get Started — It's Free <ArrowRight className="w-5 h-5 ml-2" />
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="py-12 section-padding bg-surface-50 dark:bg-surface-950">
        <div className="max-w-6xl mx-auto grid md:grid-cols-4 gap-8">
          <div className="md:col-span-2">
            <div className="flex items-center gap-2 text-base font-semibold mb-3">
              <Brain className="w-5 h-5 text-primary-500" />
              InterviewAI
            </div>
            <p className="text-sm text-[var(--color-text-secondary)] max-w-md leading-relaxed">
              AI-powered mock interviews for aptitude, technical, HR, and
              managerial rounds. Practice consistently, improve faster, and walk
              into interviews with confidence.
            </p>
            <div className="flex items-center gap-3 mt-4">
              <a
                href="#"
                className="p-2 rounded-lg bg-surface-100 dark:bg-surface-800 hover:bg-surface-200 dark:hover:bg-surface-700 transition-colors"
                aria-label="GitHub"
              >
                <Github className="w-4 h-4" />
              </a>
              <a
                href="#"
                className="p-2 rounded-lg bg-surface-100 dark:bg-surface-800 hover:bg-surface-200 dark:hover:bg-surface-700 transition-colors"
                aria-label="LinkedIn"
              >
                <Linkedin className="w-4 h-4" />
              </a>
              <a
                href="mailto:support@interviewai.com"
                className="p-2 rounded-lg bg-surface-100 dark:bg-surface-800 hover:bg-surface-200 dark:hover:bg-surface-700 transition-colors"
                aria-label="Email"
              >
                <Mail className="w-4 h-4" />
              </a>
            </div>
          </div>

          <div>
            <h4 className="text-sm font-semibold mb-3">Product</h4>
            <ul className="space-y-2 text-sm text-[var(--color-text-secondary)]">
              <li>
                <Link to="/register" className="hover:text-[var(--color-text)]">
                  Start Free
                </Link>
              </li>
              <li>
                <Link to="/login" className="hover:text-[var(--color-text)]">
                  Dashboard
                </Link>
              </li>
              <li>
                <span>Analytics</span>
              </li>
              <li>
                <span>Interview History</span>
              </li>
            </ul>
          </div>

          <div>
            <h4 className="text-sm font-semibold mb-3">Resources</h4>
            <ul className="space-y-2 text-sm text-[var(--color-text-secondary)]">
              <li>
                <span>Interview Tips</span>
              </li>
              <li>
                <span>Question Types</span>
              </li>
              <li>
                <span>Privacy</span>
              </li>
              <li>
                <span>Terms</span>
              </li>
            </ul>
          </div>
        </div>

        <p className="max-w-6xl mx-auto mt-8 text-sm text-[var(--color-text-tertiary)] text-center">
          Copyright 2026 InterviewAI
        </p>
      </footer>
    </div>
  );
}
